require_relative('./models/customers.rb')
require_relative('./models/films.rb')
require_relative('./models/tickets.rb')

require('pry-byebug')

Ticket.delete_all()
Customer.delete_all()
Film.delete_all()

customer1 = Customer.new ({'name' => 'Greg', 'funds' => '20'})
customer1.save()
customer2 = Customer.new ({'name' => 'Richard', 'funds' => '15'})
customer2.save()
customer3 = Customer.new ({'name' => 'Steve', 'funds' => '25'})
customer3.save()
customer4 = Customer.new ({'name' => 'Jim', 'funds' => '20'})
customer4.save()

film1 = Film.new ({'title' => 'Goodfellas', 'price' => '8'})
film1.save()
film2 = Film.new ({'title' => 'Jumanji', 'price' => '7'})
film2.save()
film3 = Film.new ({'title' => 'Indiana Jones', 'price' => '5'})
film3.save()

ticket1 = Ticket.new ({'customer_id' => customer1.id, 'films_id' => film1.id})
ticket1.save()
ticket2 = Ticket.new ({'customer_id' => customer1.id, 'films_id' => film2.id})
ticket2.save()
ticket3 = Ticket.new ({'customer_id' => customer2.id, 'films_id' => film1.id})
ticket3.save()
ticket4 = Ticket.new ({'customer_id' => customer3.id, 'films_id' => film1.id})
ticket4.save()
ticket5 = Ticket.new ({'customer_id' => customer4.id, 'films_id' => film1.id})
ticket5.save()
ticket6 = Ticket.new ({'customer_id' => customer3.id, 'films_id' => film2.id})
ticket6.save()
ticket7 = Ticket.new ({'customer_id' => customer4.id, 'films_id' => film2.id})
ticket7.save()
ticket8 = Ticket.new ({'customer_id' => customer1.id, 'films_id' => film3.id})
ticket8.save()
ticket9 = Ticket.new ({'customer_id' => customer4.id, 'films_id' => film3.id})
ticket9.save()

binding.pry
nil
